### ISSUE TITLE
USER STORY: FEEDBACK

### ISSUE THREAD

**Issue by Oliver-Tommy** [Oliver-Tommy/love-running#2]
As a **user** I can **vote anonymously** so that **I am more likely to vote**

## Acceptance Criteria
- Acceptance Criteria 1: Add a checkbox to vote anonymously
- Acceptance Criteria 2: Make that checkbox checked by default
- Acceptance Criteria 3: The option should appear by the submit button

## Tasks
- [ ] Create checkbox by submit button
- [ ] Give the checkbox a title
- [ ] Make checkbox selected by default
